### PR TITLE
Support for Symfony 4.3 EventDispatcher->dispatch definition

### LINKED ISSUE #77: Memory consumption in Symfony 4.3
I was trying to move to 4.3 from 4.2 and the memory consumption of this bundle is through the roof. Does anyone has any idea what could cause this ?

### PR DESCRIPTION
**Pull request by Pirokiko**
Fix #77 : Huge memory consumption

The definition of the Eventdispatcher->dispatch function has been changed in Symfony 4.3, throwing a deprecation warning.
For large data sets, this means that this deprecation warning is thrown a whole lot of times which takes up a surprising amount of memory.

### CODE REVIEW

**Review by florentdestremau — APPROVED** [review]

**Comment by mwarnaar** [comment]
@viniychuk Any chance of updating this merge request/commit to packagist?

**Comment by florentdestremau** [comment]
I asked on the original issue and no answer for now.

Your can use this line in your composer.json to be up-to-date with master:

```
        "youshido/graphql-bundle": "dev-master#5f192e7cab00710b03e4dd24169e5cdb32b5fcb6"
```

**Comment by viniychuk** [comment]
Hi, it has been updated, but Packagist hooks didn't work — had to re-connect them. 
Any of you guys interested in getting write permissions to repo?

**Comment by mwarnaar** [comment]
Cheers

**Pull request merged**
