### PR TITLE
Added event system to GraphQL

### PR DESCRIPTION
**Pull request by keesschepers**
In our situation we need to monitor performance with new relic. Therefore I created an event dispatcher to monitor the resolving of various fields with pre and post events.

Any feedback is very welcome.

### CODE REVIEW

**Comment by viniychuk** [comment]
@keesschepers looks good. My only question for now – do you think it would be helpful to include `astFields` to the event as well?

**Comment by keesschepers** [comment]
Thanks @viniychuk! I will create a custom Event class and indeed add astFields property and setter/getter. Will update the pull-request quickly.

**Comment by keesschepers** [comment]
@viniychuk I updated the pull-request with a domain specific event object and updated the README.md. Could you check again? If you want me to squash the commits please tell me so.

**Comment by viniychuk** [comment]
@keesschepers thanks, looks good.

**Pull request merged**
